name: keyboard_action
description: custom keyboard action
version: 0.0.1
homepage: https://github.com/ho-doan/keyboard_action

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protobuf: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.hodoan.keyboard_action
        pluginClass: KeyboardActionPlugin
      ios:
        pluginClass: KeyboardActionPlugin